-- ==========================================================
-- 100 WAANO (COACHING TIPS) - BEST OFFICIAL APP
-- Run this in Supabase SQL Editor to populate all 100 tips
-- ==========================================================

INSERT INTO tips (text, sort_order)
VALUES
  ('Kalsooni naftaada isku hallee — waxaad ka baran doontaa khaladaadka.', 1),
  ('Tababarka joogtada ah ayaa kaa dhiga ciyaaryahan wanaagsan.', 2),
  ('Hurdo ku filan (7-9 saacadood) ayaa jirkaaga u sahleysa soo kabashada.', 3),
  ('Biyo badan cab — jidhku wuxuu u baahan yahay biyo si uu si fiican u shaqeeyo.', 4),
  ('Cunto nafaqo leh cun ka hor iyo ka dib tababarka.', 5),
  ('Kulaylin (warm-up) ka hor ciyaarta si aad naftaada uga ilaaliso dhaawac.', 6),
  ('Qabow-gelin (cool-down) ka dib tababarka waa muhiim.', 7),
  ('Dhageyso talooyinka kabtanka — hagashadiisu wax bay kuu tari doontaa.', 8),
  ('Ha ka baqin inaad khalad gasho — khaladku waa qeyb ka mid ah barashada.', 9),
  ('Ku celceli xirfadaha aasaasiga ah sida gudbinta iyo xakamaynta.', 10),
  ('Ciyaar kasta u tababaro sidii mid ugu weyn.', 11),
  ('Ixtiraam garoonka, agabka, iyo saaxiibbadaada.', 12),
  ('Anshax wanaagsan ayaa kaa dhigi kara xidiga kooxda.', 13),
  ('Timirka guusha waa isku-duub, ma aha hal qof.', 14),
  ('Ha ku kalsoonaan xirfad keliya — isku day inaad wax walba baratid.', 15),
  ('Waqtiga dib-u-eegista fiidyowga ciyaarahaaga ku isticmaal si aad u hagaajiso.', 16),
  ('Rux jirkaaga joogtada ah, xitaa maalmaha aan tababarku jirin.', 17),
  ('Ha isbarbardhigin nafta kuwa kale — koritaankaaga qudhaada ku fiirso.', 18),
  ('Xoogaaga maskaxeed dhis — ciyaartu waa maskax iyo jidhba.', 19),
  ('Aqbal in la canaanto — canaantu waxay kuu tusaysaa jidka wanaagsan.', 20),
  ('Waqti gaar ah u qabso inaad hal-abuurato garoonka banaan.', 21),
  ('La kulan cabsida — ciyaartoyda ugu fiican waa kuwa aan ka baqin qalad.', 22),
  ('Isha xir sawirka aad rabto inaad noqoto, kadibna u shaqee.', 23),
  ('Ku faan ciyaartoyda kale hagaajintooda, ha isbarbardhigin.', 24),
  ('Dulqaad — guulu waa arrin waqti qaadata.', 25),
  ('Xasuuso: wax kasta oo aad barato garoonka wuxuu kuu taraa nolosha guud ahaan.', 26),
  ('Marka aad dhaawacantid, ha degdegin — sug in jidhku bogsado.', 27),
  ('Aqoonta taktikada kooxda si buuxda u fahan.', 28),
  ('Codso su''aalo marka aad wax fahmi weyso — waa xoog, ma aha itaal-daro.', 29),
  ('Ka fogow walbahaarka — kalsoonidu waxay ku dhalataa sameyn joogto ah.', 30),
  ('Xushmee kabtanka iyo tababarayaasha xitaa marka aysan kula qabsanayn.', 31),
  ('Ku farxi guusha kooxda intii aad ku farxi lahayd midkaaga gaarka ah.', 32),
  ('Ka fiirso ciyaartada u yaal fiidyowga ciyaartoyda caanka ah.', 33),
  ('Xoogaaga saaxiibtinimo dhis kooxda dhexdeeda.', 34),
  ('Ha u fasaxin naftaada inaad joojiso marka wax ku adkaadaan.', 35),
  ('Habka fekerkaaga hagaaji — fikir wanaagsanu wuxuu horseedaa ficil wanaagsan.', 36),
  ('Beryahaan fasaxa ah ku qabso dhaqdhaqaaq jidh ah, xitaa mid fudud.', 37),
  ('Isu diyaari maskax ahaan kahor ciyaar kasta.', 38),
  ('Ka faa''iideyso khaladaadka aad kaga guuldareysatay ciyaaraha hore.', 39),
  ('Ku dhiirrado inaad la hadasho kabtanka haddii aad wax ka qabto.', 40),
  ('Ha ilaawin salaadda iyo waajibaadka diinta xitaa xilliga tababarka.', 41),
  ('Waqtigaaga si sax ah u maamul — waxbarasho iyo ciyaar labaduba waa muhiim.', 42),
  ('Habsami u dhis jidhkaaga — cimri-dherer ciyaareed waa laga xilliyeeyaa.', 43),
  ('Ha ka quusan haddii aad hal ciyaar ku guuldareysato.', 44),
  ('Ka fikir sida aad kooxda ugu adeegi karto, ma aha sida kaliya aad naftaada u qurxin karto.', 45),
  ('Aqbal in kabtanku ku badalo goobta — waa qeyb ka mid ah tababarka.', 46),
  ('Waalidkaaga la wadaag guulaha iyo dhibaatooyinka kula kulmaya.', 47),
  ('Aqoonso xilliga aad nasasho u baahan tahay — jirku wuu kuu sheegayaa.', 48),
  ('Kalsoonida kooxda si joogto ah u dhis — waa aasaaska guusha.', 49),
  ('Sii wad — mustaqbalka wanaagsan wuxuu ka bilaabmaa dadaalka maanta.', 50),
  ('Miyir iyo digtoonaan buuxi garoonka, xitaa marka aad tababar fudud qabanayso.', 51),
  ('Ha isticmaalin taleefanka intii tababarku socdo.', 52),
  ('Booqasho joogto ah oo dhakhtar ay wanaagsan tahay haddii aad dhaawac soo jireen ah qabto.', 53),
  ('Sheekaysi kabtanka mashaakilaadka guriga haddii ay saameyn ku yeelan karaan waxqabadkaaga.', 54),
  ('Xoogaaga ku bixi tababarka, ha u kaydin ciyaarta kaliya.', 55),
  ('Aqbal doorka lagu siiyay, xitaa haddii aanad rabin.', 56),
  ('Xasuuso in kubadda cagta ay tahay ciyaar kooxeed, ma aha mid shakhsi ah.', 57),
  ('Iska ilaali khilaaf kula kici kara saaxiibbadaada garoonka dibadiisa.', 58),
  ('U sheeg kabtanka haddii aad shaqo/xaajo kale qabatid oo aanad iman doonin tababarka.', 59),
  ('Marka aad ciyaaraysid, is fiirso — sida aad u dhaqdhaqaaqdo ayaa saameyn ku yeelan karta ciyaartada.', 60),
  ('Baro sida loo ilaaliyo kubadda si aan looga kaadin.', 61),
  ('Isticmaal labada lugood, ha ku kalsoonaan hal lug oo keliya.', 62),
  ('Sii wad tababarka xitaa marka roob da''ayo — waa qeyb ka mid ah tayada.', 63),
  ('Xushmee xakamiyaha (referee-ga) xitaa haddii aad qabin go''aankiisa.', 64),
  ('Ku celceli xoojinta jirka (fitness) si aad u sii xoogaysato.', 65),
  ('Sheeko la yeelo asxaabtaada tababarka ka dib — waxaad wax badan ka barataa.', 66),
  ('Isha ku hay kubadda marka aad la ciyaarayso, ha eegin cida kale.', 67),
  ('Xasuuso in kastoo kooxdu ay guuleysato, adiguna waad guuleysatay.', 68),
  ('Ha ka fikirin natiijada kaliya — geeddi-socodku (process-ka) ayaa muhiim ah.', 69),
  ('U diyaargarow ciyaar kasta sidii aad ugu diyaargarowdo tijaabo waxbarasho.', 70),
  ('Bar naftaada inaad kalsoonaan la fal-galiso cabsi kasta oo kula kulanta garoonka.', 71),
  ('Booqo saaxiibbadaada kooxda marka ay dhaawacmaan — waa taageero.', 72),
  ('Ka fiirso fiidyowyada tababarka ee kooxaha caanka ah, ka barasho ahaan.', 73),
  ('Ku celceli xijaabta iyo taktikada goolka gudihiisa.', 74),
  ('Sheeg run haddii aad khalad gashay — waa xoog ma aha itaal daro.', 75),
  ('Kalsoonida naftaada dhis adigoo dib u eegaya waxqabadyadaada hore.', 76),
  ('Marka aad ku adkaato garoonka, xasuuso arrimaha wanaagsan ee aad hore u samaysay.', 77),
  ('Ka fogow luuqad xun oo lagu hadlo garoonka dhexdiisa.', 78),
  ('Xasuuso in kabtanku doonayo inuu ku hagaajiyo, ma aha inuu ku dhibo.', 79),
  ('Waqti gaar ah u qabso inaad la shaqeyso xubnaha kooxda aadan aad ula socon.', 80),
  ('Iyada oo aan la eegin cimriga, mid kasta wuxuu leeyahay wax uu ka bartaa kan kale.', 81),
  ('Ku dadaal inaad tahay xubin lagu kalsoonaan karo goobta iyo dibadeedaba.', 82),
  ('Ha isku daalin jirkaaga inta u dhaxaysa tababarrada — nasashadu waa qeyb ka mid ah horumarka.', 83),
  ('Xushmee waalidkaaga oo la wadaag jadwalka tababarka si ay u soo raaci karaan.', 84),
  ('Ku celi hadalada dhiiri-galinta ah naftaada ka hor ciyaar kasta.', 85),
  ('Aqbal in guushu waqti qaadan karto — ha degdegin.', 86),
  ('U adeeg saaxiibbadaada garoonka sidii aad rabto in lagu adeego.', 87),
  ('Ka fiirso qofka aad u tahay dibadda garoonka — anshaxaas ayaa kugu raaca gudaha garoonka.', 88),
  ('Bar isu-imaanshaha (coordination) adigoo la ciyaaraya kuwo kale.', 89),
  ('Xasuuso in cimriga hore ee ciyaartu uu ku horseedo mid dambe oo fiican.', 90),
  ('Iska ilaali in aad is barbardhigto kuwa kaa weyn — koritaanku waa mid gaar ah.', 91),
  ('Ka faa''iidayso xilliga fasaxa si aad naftaada u soo celiso jir ahaan iyo maskax ahaanba.', 92),
  ('Ku celceli isu dhig (positioning) garoonka si aad meesha saxda ah u joogto had iyo jeer.', 93),
  ('Xasuuso in cudurdaar la yeelan karo, laakiin waa in la ilaaliyo si aan loo horumarin dhaqan xun.', 94),
  ('Aqoonso saaxiibbadaada kuwa kula shaqeeya si fiican garoonka dushiisa.', 95),
  ('Ha ka quusan haddii aad ma ahayn qofka la doortay kulan gaar ah — waqtigaaga wuu iman doonaa.', 96),
  ('U hoggaanso naftaada dhaqan sax ah xitaa marka aan cidina ku eegin.', 97),
  ('Xasuuso astaanta koox — sawirkaaga waa sawirka kooxda oo dhan.', 98),
  ('Ka fikir sida aad u caawin karto kuwa cusub ee ku biira kooxda.', 99),
  ('Isticmaal khaladaadka kuwa kale sidii waanooyin, ma aha sidii jeesjees.', 100);
